### ISSUE TITLE
Customizing TimelineItem component

### ISSUE THREAD

**Issue by SalahAdDin** [pk12/material-timeline#5]
As  you can see in the next image, we are not requiring the card styles but different decorators for the items:
![image](https://user-images.githubusercontent.com/5034215/79502246-047c4b80-8038-11ea-8af2-e5a522ff32e6.png)

As far as i understand, it is not possible to change the component we want to render as the item component, this could be a very good feature.

What do you think?

**Comment by pkanellidis** [comment]
Hi,
Yes right now there isn't such functionality in order to keep it simple but it can be changed.
There is a div wrapping this item so the functionality could be extended to passing your item as a prop and if there is no prop, then use the current one as default.

**Comment by SalahAdDin** [comment]
@pk12 Could be possible to change the size of the [lines](https://github.com/pk12/material-timeline/blob/ceeb2cbba1ff27fa3937c8f0f01b8bd1b642ef86/src/lib/TimelineItem/TimelineItem.js#L69)?

It would be great for customizing the timeline style.

Also it would be great making another option for `side` option: `both`.

**Comment by pkanellidis** [comment]
@SalahAdDin You can already customize the line if you see the code that you mentioned, the component accepts a customLine property.
How would `both `work?

**Comment by SalahAdDin** [comment]
Title in one side and text in the other side.

**Comment by pkanellidis** [comment]
It's very possible, it would take one new type of TimelineItem and I recall you mentioning it in another issue but I don't have the time to implement it right now. Will do so in the future, I am already in the process of implementing the current issue as I was already planning to do so.

**Comment by SalahAdDin** [comment]
@pk12 Another issue could be in the final `TimelineItem` should not follow a line, the last node must be the last decorative.

**Comment by SalahAdDin** [comment]
@pk12 Could be a good idea to put any way to delete the line styles?

**Comment by pkanellidis** [comment]
@SalahAdDin You can just enter an empty customLine whenever you don't want the line to show (e.g. Last element).
![image](https://user-images.githubusercontent.com/407006/79682705-0bb87a80-822d-11ea-8513-527ff48a9e3a.png)

**Comment by SalahAdDin** [comment]
I got to change the `timelineYear` component by using: `classes={{ timelineYear: classes.iconNumberStyle }}`.

But when the padding is to low i get this:
![image](https://user-images.githubusercontent.com/5034215/79796115-a6b07200-835d-11ea-80d4-5696137fd012.png)

It is related to the upper component margin or padding, increasing the line height to 110% could be a monkey patch solution.

**Comment by SalahAdDin** [comment]
Here, the same problem with another setup:
![image](https://user-images.githubusercontent.com/5034215/79866591-acea3100-83e5-11ea-9a22-f976ec52d991.png)

**Comment by pkanellidis** [comment]
I am creating a new Implementation of these lines that should fix these problems, will need some time though

**Comment by SalahAdDin** [comment]
Would it change the whole structure? because i based my solution in the current structure.

**Comment by pkanellidis** [comment]
@SalahAdDin So after digging into it, the whole problem is created because of the bad usage of the component.

- The bad alignment at the beginning occurs because of the nested TimelineItems that you create, you shouldn't pass an array of 2 elements inside the Timeline but only a shallow array of TimelineItems with a simple .map function that returns a TimelineItem, If that does not fix the problem, then it may be the fault of some custom styling.
<img width="339" alt="Screenshot 2020-04-21 at 8 19 57 PM" src="https://user-images.githubusercontent.com/407006/79894023-85a75a00-840d-11ea-8054-6ecabeba74b2.png"> As you can see I get no such behavior.

- All the weird behavior that you get by bypassing the styling of the component isn't something that can be supported because the component was not meant to be used like this. If you can find a way to bypass it without any problems then do so.

**Comment by SalahAdDin** [comment]
The problem, with small dots, is the padding: it must be big padding.

After reviewing the code i got the problem is more with style instead to a full array; i mean if I remove all custom styles i don't get this bug, but if i modify the `year` component style i will get those problems.
